POST localhost:8080/api/attach/public/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image.png"

C:\Users\Acer\Pictures\Saved Pictures\123.jpg

###
DELETE http://localhost:8080/api/attach/delete/3
