### create new doctor Tashkent

POST localhost:8080/api/doctortashkent/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQzODQzMjIsInVzZXJuYW1lIjoiYWRtaW5qb24iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY3NDk4OTEyMiwiaXNzIjoiRG9uaXlvclNoaWZvIGtsaW5pa2EifQ.MtTyuCJXbnA6XgIjB1VvVF4ub0CG5sJB7ew7GInvxUvYPnzqZkmKnZYlgjsGSjXUngeF0QQiyI5lxwJtK-DSbQ
Accept-Language: UZ
Content-Type: application/json

{
  "firstName_uz": "faw",
  "firstName_ru": "safas ",
  "lastName_uz": "Mamatqdwaulov",
  "lastName_ru": "fawfwa  ",
  "speciality_uz": "fwa",
  "speciality_ru": "asfas  ",
  "phone": "+998993459406",
  "experience": 2,
  "description_uz": "Quloq davolash ishlarini amalga oshiradi",
  "description_ru": "Выполняет лечение ушей ",
  "photoId": 6
}

### Get By id Doctor Tashkent
GET localhost:8080/api/doctortashkent/public/get/4
Accept-Language: RU

### Delete By id Doctor tashkent ADMIN
DELETE localhost:8080/api/doctortashkent/delete/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzM1MDk0NzAsInVzZXJuYW1lIjoiYWRtaW5qb24iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY3NDExNDI3MCwiaXNzIjoiRG9uaXlvclNoaWZvIGtsaW5pa2EifQ.64Zc4EKyRnD1ImUphLKYhE6akcxKdQXHcdng54tTZQHAnKwELo6y59DsVYX65lvC-TR8BXBeoO9dSB6KPhhiHw
Accept-Language: UZ

### Doctor Sirdarya List Pagination
GET localhost:8080/api/doctortashkent/public/getpage
Accept-Language: RU